use longhand notation

diff --git a/bin/nmap-mac-prefixes-init b/bin/nmap-mac-prefixes-init
--- a/bin/nmap-mac-prefixes-init
+++ b/bin/nmap-mac-prefixes-init
@@ -38,8 +38,10 @@ done
 set -- "${_POSITIONAL[@]}"
 
 main() {
-  [[ -r "$1" && "$(basename "$1")" == 'nmap-mac-prefixes' ]] \
-    || (echo "Sorry, could not read nmap-mac-prefixes file"; exit 1)
+  if ! [[ -r "$1" && "$(basename "$1")" == 'nmap-mac-prefixes' ]]; then
+    echo "Sorry, could not read nmap-mac-prefixes file"
+    exit 1
+  fi
   cp "$1" resources/
 }
 
